[phases.setup]
nixPkgs = [
    'python311', 
    'pkg-config', 
    'libGL', 
    'glib', 
    'gtk3', 
    'xorg.libSM',
    'xorg.libXext',
    'xorg.libXrender',
    'gcc',
    'zlib',
    'libffi',
    'openssl',
    'glibc'
]

[phases.install]
cmds = [
    'pip install --upgrade pip setuptools wheel',
    'pip install --no-cache-dir torch==2.0.1+cpu torchvision==0.15.2+cpu -f https://download.pytorch.org/whl/torch_stable.html',
    'pip install --no-cache-dir ultralytics==8.0.196',
    'pip install --no-cache-dir opencv-python-headless==4.8.1.78',
    'pip install --no-cache-dir scikit-learn==1.3.0',
    'pip install --no-cache-dir tensorflow-cpu==2.13.0',
    'pip install --no-cache-dir -r requirements.txt'
]

[phases.build]
cmds = [
    'mkdir -p frames',
    'mkdir -p yolo_crop_clustering', 
    'mkdir -p processed_video_result',
    'mkdir -p static',
    'mkdir -p templates'
]

[start]
cmd = 'python main.py'

[variables]
PYTHONUNBUFFERED = '1'
FLASK_ENV = 'production'
PORT = '8080'
